const education = [
  {
    program: "Frontend Developer",
    school: "Medieinstitutet",
    duration: "2024–ongoing",
    courses: [
      { name: "HTML and CSS", credits: "20 YHP" },
      { name: "UX/Usability", credits: "15 YHP" },
      { name: "JavaScript – Introductory Course", credits: "40 YHP" },
      { name: "Agile Project Work", credits: "10 YHP" },
      { name: "Graphic Tools for UI Design", credits: "15 YHP" },
      { name: "Work Methodology for Developers", credits: "15 YHP" },
      { name: "API Development", credits: "45 YHP" },
      { name: "JavaScript – Advanced Course", credits: "60 YHP" },
    ],
  },
  {
    program: "Webmaster (120 ECTS)",
    school: "University West (Högskolan Väst)",
    duration: "2022–2024",
    courses: [
      { name: "Degree Project", credits: "7.5 ECTS" },
      { name: "Research Methodology", credits: "7.5 ECTS" },
      { name: "Development of Mobile Web Applications", credits: "7.5 ECTS" },
      { name: "Website Administration and Marketing", credits: "7.5 ECTS" },
      { name: "Content Management Systems", credits: "7.5 ECTS" },
      { name: "JavaScript Frameworks", credits: "7.5 ECTS" },
      { name: "Applied Database Management", credits: "7.5 ECTS" },
      { name: "Web Programming", credits: "7.5 ECTS" },
      { name: "Design Processes for Digital Projects", credits: "7.5 ECTS" },
      { name: "Security and Privacy Online", credits: "7.5 ECTS" },
      { name: "Media for the Web", credits: "7.5 ECTS" },
      {
        name: "Advanced Web Development with HTML and CSS",
        credits: "7.5 ECTS",
      },
      { name: "Basic JavaScript Programming", credits: "7.5 ECTS" },
      {
        name: "Intranet/Internet – Services and Networks",
        credits: "7.5 ECTS",
      },
      { name: "Web Development with HTML and CSS", credits: "7.5 ECTS" },
      { name: "Graphic Design for the Web", credits: "7.5 ECTS" },
    ],
  },
];
