export const EMAIL = "edchy@proton.me";

export const navItems = [
  { name: "about", path: "/me" },
  { name: "blog", path: "/blog" },
  { name: "work", path: "/work" },
  // { name: "news", path: "/blog" },
  { name: "fun", path: "/fun" },
];
export const devPlain = {
  icon: "devicon-plain",
  names: [
    "angularjs",
    "apache",
    "astro",
    "axios-wordmark",
    "bash",
    "babel",
    "bun",
    "c",
    "css3",
    "django",
    "debian",
    "firebase",
    "figma",
    "git",
    "html5",
    "javascript",
    "jquery",
    "mongodb",
    "mysql-wordmark",
    "nextjs",
    "npm",
    "php",
    "postman",
    "pnpm",
    "sanity",
    "sqlite",
    "svelte",
    "styledcomponents",
    "tailwindcss-wordmark",
    "typescript",
    "vitejs",
    "vuejs",
  ],
};

export const catppuccin = {
  icon: "catppuccin",
  names: [
    "angular",
    "typescript-react",
    "apache",
    "babel",
    "astro",
    "c",
    "bun",
    "css",
    "bash",
    "deno",
    "django",
    "drizzle-orm",
    "figma",
    "firebase",
    "git",
    "html",
    "javascript",
    "markdown",
    "next",
    "netlify",
    "prettier",
    "php",
    "npm",
    "pug",
    "sass",
    "svelte",
    "tailwind",
    "typescript",
    "vite",
    "vue",
  ],
};
export const devicon = {
  icon: "devicon",
  names: [
    "javascript",
    "typescript",
    "nodejs",
    "html5",
    "css3",
    "tailwindcss",
    "sass",
    "react",
    "astro",
    "figma",
    "git",
    "github",
    "mysql",
    "mongodb",
    "mongoose",
    "firebase",
    "nextjs",
    "vuejs",
    "svelte",
    "php",
    "expo",
    "apache",
    "babel",
    "jquery",
    "zsh",
    "netlify",
    "vercel",
    "vitejs",
    "npm",
  ],
};
