export const navItems = [
  { name: "me", path: "/me" },
  { name: "blog", path: "/blog" },
  { name: "fun", path: "/blog" },
  // { name: "news", path: "/blog" },
  { name: "tags", path: "/tags" },
];

export const deviconNames = [
  "javascript",
  "typescript",
  "nodejs",
  "html5",
  "css3",
  "tailwindcss",
  "sass",
  "react",
  "astro",
  "figma",
  "git",
  "github",
  "mysql",
  "mongodb",
  "mongoose",
  "firebase",
  "nextjs",
  "vuejs",
  "svelte",
  "php",
  "expo",
  "apache",
  "babel",
  "jquery",
  "zsh",
  "netlify",
  "vercel",
  "vitejs",
  "npm",
];
