export const EMAIL = "edchy@proton.me";
export const pageInfo = {
  title: "Nope Studio",
  description:
    "At Nope, we design and develop websites and apps that are easy on the eyes, fun to use, and actually do what they’re supposed to.",
};

export const navItems = [
  { name: "about", path: "/me" },
  { name: "blog", path: "/blog" },
  { name: "work", path: "/work" },
  // { name: "news", path: "/blog" },
  { name: "fun", path: "/fun" },
];
export const devicon = {
  icon: "devicon",
  names: [
    "angular",
    "apache",
    "astro",
    "babel",
    "bun",
    "c",
    "css3",
    "debian",
    "eleventy",
    "expo",
    "express",
    "figma",
    "firebase",
    "ghost",
    "git",
    "homebrew",
    "html5",
    "javascript",
    "jquery",
    "markdown",
    "mongodb",
    "mysql",
    "netlify",
    "nextjs",
    "nodejs",
    "npm",
    "php",
    "python",
    "react",
    "reactnative-wordmark",
    "sanity",
    "sass",
    "sentry",
    "solidjs",
    "sqlite",
    "styledcomponents",
    "supabase",
    "swagger",
    "svelte",
    "tailwindcss",
    "typescript",
    "vitejs",
    "vuejs",
    "vercel",
  ],
};
export const devPlain = {
  icon: "devicon-plain",
  names: [
    "tailwindcss-wordmark",
    "axios-wordmark",
    "mysql-wordmark",
    "babel",
    "angularjs",
    "apache",
    "astro",
    "bash",
    "bun",
    "c",
    "css3",
    "django",
    "debian",
    "firebase",
    "figma",
    "git",
    "html5",
    "javascript",
    "jquery",
    "mongodb",
    "nextjs",
    "npm",
    "php",
    "postman",
    "pnpm",
    "sanity",
    "sqlite",
    "svelte",
    "styledcomponents",
    "typescript",
    "vitejs",
    "vuejs",
  ],
};

export const catppuccin = {
  icon: "catppuccin",
  names: [
    "apache",
    "svelte",
    "babel",
    "astro",
    "typescript-react",
    "tailwind",
    "c",
    "typescript",
    "php",
    "markdown",
    "bun",
    "css",
    "redwood",
    "sentry",
    "solid",
    "python",
    "markdown-mdx",
    "vue",
    "bash",
    "django",
    "drizzle-orm",
    "figma",
    "deno",
    "npm",
    "angular",
    "git",
    "html",
    "javascript",
    "firebase",
    "next",
    "netlify",
    "prettier",
    "pug",
    "sass",
    "vite",
  ],
};
